# Generated by Django 5.1.5 on 2025-01-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lps_usertable',
            },
        ),
    ]
